### ISSUE TITLE
Plugins need to be able to take configuration

### ISSUE THREAD

**Issue by AaronC81** [AaronC81/parlour#18]
**Is your feature request related to a problem? Please describe.**
While thinking of how to create a Sequel plugin, I realised that I needed a way of specifying the entry point for the application to the plugin.

**Describe the solution you'd like**
Plugins need to be able to take configuration options somehow. I think the most sensible way to do this is to have plugins defined in a YAML file, rather than as command-line options. Something like:

```yaml
out: rbi/app.rbi

gems:
  - parlour-sequel

plugins:
  ParlourSequel:
    entry: src/app.rb
```

Invoking `parlour` would then load options from this file.

**Describe alternatives you've considered**
Each plugin could have its own configuration file, but this would be very awkward.
